[DNM] drivers: mtk: flashlight: sm5714: hack in (redundant, unused) sm5714_adjust_voltage type
../drivers/misc/mediatek/flashlight/flashlights-sm5714.c:353:2: error: incompatible function pointer types assigning to 'work_func_t' (aka 'void (*)(struct work_struct *)') from 'void (void)' [-Werror,-Wincompatible-function-pointer-types]
        INIT_WORK(&sm5714_voltage_work, sm5714_adjust_voltage);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/workqueue.h:238:2: note: expanded from macro 'INIT_WORK'
        __INIT_WORK((_work), (_func), 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/workqueue.h:233:17: note: expanded from macro '__INIT_WORK'
                (_work)->func = (_func);                                                              ^ ~~~~~~~
1 error generated.

Signed-off-by: fukiame <fukiame@proton.me>